name: zeta_widgetbook
description: "Widgetbook for zeta_flutter"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2
  http: ^1.6.0
  markdown_widget: ^2.3.2+8
  url_launcher: ^6.3.2
  widgetbook: ^3.20.0
  widgetbook_annotation: ^3.9.0
  zeta_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.20.0
  build_runner: ^2.10.3

flutter:
  uses-material-design: true
  assets:
    - assets/
