name: zeta_flutter
version: 1.4.2
description: Zeta is the new, formal, standardized Zebra Design System based off the successes of ZDS (Zebra Design System).
homepage: https://design.zebra.com
repository: https://github.com/zebradevs/zeta_flutter/tree/main/packages/zeta_flutter
issue_tracker: https://github.com/zebradevs/zeta_flutter/issues

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  audioplayers: ^6.5.1
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.2.2
  http: ^1.6.0
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.5+1
  record: ^6.1.2
  zeta_flutter_theme: ^1.2.3
  zeta_flutter_utils: ^1.1.4
  zeta_icons: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  image: ^4.5.4
  mockito: ^5.5.1
  path: ^1.9.1
  zds_analysis: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/flags/
    - assets/logos/
